services:
  postgres:
    image: postgres:14.5
    command: postgres -c 'max_connections=200'
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "administrator"
      POSTGRES_DB: "psychodiary"
      POSTGRES_PASSWORD: "Penkina"